"""
train_vit.py

Training and evaluation pipeline for the temporal ViT damage classifier.

Input  : pre_prob + post_prob maps generated by infer_unet.py
Labels : 3-class derived from U-Net pre-war output + UNOSAT ground truth
           0 = undamaged
           1 = newly damaged
           2 = pre-existing damage
"""

import random
import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from PIL import Image

ROOT       = Path(__file__).parent.parent
PATCH_DIR  = ROOT / "data" / "patches"
MODEL_DIR  = ROOT / "models";   MODEL_DIR.mkdir(exist_ok=True)
RESULTS_DIR = ROOT / "results"; RESULTS_DIR.mkdir(exist_ok=True)

CKPT_PATH   = MODEL_DIR  / "temporal_vit_best.pth"
CURVE_PATH  = RESULTS_DIR / "vit_loss_curves.png"
EVAL_PATH   = RESULTS_DIR / "vit_eval.png"

sys.path.insert(0, str(ROOT / "src"))
from temporal_vit import TemporalViT, derive_labels, PRE_THRESH

# ── Hyper-parameters ──────────────────────────────────────────────────────────
EPOCHS      = 50
BATCH_SIZE  = 16
LR          = 2e-4
VAL_FRAC    = 0.2
SEED        = 42
NUM_CLASSES = 3
CITIES      = ["kharkiv", "mariupol"]


# ── Device ────────────────────────────────────────────────────────────────────
def get_device():
    if torch.backends.mps.is_available(): return torch.device("mps")
    if torch.cuda.is_available():         return torch.device("cuda")
    return torch.device("cpu")


# ── Dataset ───────────────────────────────────────────────────────────────────
class TemporalDataset(Dataset):
    """
    Returns:
        x      : (2, H, W) float — [pre_prob, post_prob]
        labels : (H, W)    long  — 0/1/2 per pixel
    """
    def __init__(self, samples: list[tuple], augment: bool = False):
        self.samples = samples
        self.augment = augment

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        city, pid = self.samples[idx]

        pre_prob  = torch.from_numpy(
            np.load(PATCH_DIR / city / "pre_prob"  / f"{pid}.npy"))
        post_prob = torch.from_numpy(
            np.load(PATCH_DIR / city / "post_prob" / f"{pid}.npy"))
        mask_arr  = np.array(
            Image.open(PATCH_DIR / city / "masks" / f"{pid}.png").convert("L"),
            dtype=np.float32) / 255.0
        unosat    = torch.from_numpy(mask_arr)

        labels = derive_labels(pre_prob, unosat, threshold=PRE_THRESH)  # (H,W) long

        x = torch.stack([pre_prob, post_prob], dim=0).float()  # (2, H, W)

        if self.augment:
            if random.random() < 0.5:
                x, labels = x.flip(-1), labels.flip(-1)   # horizontal flip
            if random.random() < 0.5:
                x, labels = x.flip(-2), labels.flip(-2)   # vertical flip
            if random.random() < 0.5:
                k = random.randint(1, 3)
                x = torch.rot90(x, k, [-2, -1])
                labels = torch.rot90(labels, k, [-2, -1])

        return x, labels


def make_splits():
    all_samples = []
    for city in CITIES:
        ids = sorted(p.stem for p in (PATCH_DIR / city / "pre_prob").glob("*.npy"))
        all_samples += [(city, pid) for pid in ids]
    rng = random.Random(SEED)
    rng.shuffle(all_samples)
    n_val = max(1, int(len(all_samples) * VAL_FRAC))
    return all_samples[n_val:], all_samples[:n_val]


# ── Class weights (inverse frequency) ─────────────────────────────────────────
def compute_class_weights(train_samples):
    counts = torch.zeros(NUM_CLASSES)
    for city, pid in train_samples:
        mask_arr = np.array(
            Image.open(PATCH_DIR / city / "masks" / f"{pid}.png").convert("L"),
            dtype=np.float32) / 255.0
        pre_prob = torch.from_numpy(
            np.load(PATCH_DIR / city / "pre_prob" / f"{pid}.npy"))
        unosat   = torch.from_numpy(mask_arr)
        labels   = derive_labels(pre_prob, unosat, PRE_THRESH)
        for c in range(NUM_CLASSES):
            counts[c] += (labels == c).sum().float()
    weights = counts.sum() / (NUM_CLASSES * counts.clamp(min=1))
    return weights


# ── Training ──────────────────────────────────────────────────────────────────
def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total_loss = 0.0
    for x, labels in loader:
        x, labels = x.to(device), labels.to(device)
        optimizer.zero_grad()
        logits = model(x)                               # (B, 3, H, W)
        loss   = criterion(logits, labels)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        total_loss += loss.item() * x.size(0)
    return total_loss / len(loader.dataset)


@torch.no_grad()
def validate(model, loader, criterion, device):
    model.eval()
    total_loss = 0.0
    all_preds, all_labels = [], []
    for x, labels in loader:
        x, labels = x.to(device), labels.to(device)
        logits = model(x)
        loss   = criterion(logits, labels)
        total_loss += loss.item() * x.size(0)
        preds = logits.argmax(dim=1)
        all_preds.append(preds.cpu().flatten())
        all_labels.append(labels.cpu().flatten())
    all_preds  = torch.cat(all_preds).numpy()
    all_labels = torch.cat(all_labels).numpy()
    return total_loss / len(loader.dataset), all_preds, all_labels


# ── Evaluation plots ───────────────────────────────────────────────────────────
CLASS_NAMES  = ["Undamaged", "Newly\ndamaged", "Pre-existing"]
CLASS_COLORS = ["#EEEEEE", "#D32F2F", "#FF8F00"]  # gray, red, amber

def plot_confusion(cm, save_path):
    fig, ax = plt.subplots(figsize=(6, 5))
    im = ax.imshow(cm, interpolation="nearest", cmap="Blues")
    plt.colorbar(im, ax=ax)
    ax.set(xticks=range(NUM_CLASSES), yticks=range(NUM_CLASSES),
           xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES,
           xlabel="Predicted", ylabel="True",
           title="Confusion Matrix (normalised)")
    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True).clip(1)
    for i in range(NUM_CLASSES):
        for j in range(NUM_CLASSES):
            ax.text(j, i, f"{cm_norm[i,j]:.2f}\n({cm[i,j]:,})",
                    ha="center", va="center", fontsize=8,
                    color="white" if cm_norm[i,j] > 0.5 else "black")
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")


def plot_qualitative(model, val_samples, device, n=4):
    """Show n examples: pre_prob | post_prob | ground truth | prediction."""
    model.eval()
    rng = random.Random(42)
    chosen = rng.sample(val_samples, min(n, len(val_samples)))

    cmap_damage = plt.cm.RdYlGn_r   # green=low, red=high damage prob

    fig, axes = plt.subplots(n, 4, figsize=(14, 3.5 * n))
    col_titles = ["Pre-war prob", "Post-war prob", "Ground truth", "ViT prediction"]
    for col, title in enumerate(col_titles):
        axes[0][col].set_title(title, fontsize=11, fontweight="bold")

    import matplotlib.patches as mpatches

    for row, (city, pid) in enumerate(chosen):
        pre_prob  = np.load(PATCH_DIR / city / "pre_prob"  / f"{pid}.npy")
        post_prob = np.load(PATCH_DIR / city / "post_prob" / f"{pid}.npy")
        mask_arr  = np.array(Image.open(
            PATCH_DIR / city / "masks" / f"{pid}.png").convert("L"),
            dtype=np.float32) / 255.0

        pre_t   = torch.from_numpy(pre_prob)
        unosat  = torch.from_numpy(mask_arr)
        gt      = derive_labels(pre_t, unosat, PRE_THRESH).numpy()

        x = torch.stack([pre_t, torch.from_numpy(post_prob)], 0).unsqueeze(0).to(device)
        with torch.no_grad():
            pred = model(x).argmax(dim=1).squeeze().cpu().numpy()

        # build label RGB images
        def label_to_rgb(lbl):
            colors = np.array([[238,238,238],[211,47,47],[255,143,0]], dtype=np.uint8)
            return colors[lbl]

        axes[row][0].imshow(pre_prob,  cmap=cmap_damage, vmin=0, vmax=1)
        axes[row][1].imshow(post_prob, cmap=cmap_damage, vmin=0, vmax=1)
        axes[row][2].imshow(label_to_rgb(gt))
        axes[row][3].imshow(label_to_rgb(pred))
        axes[row][0].set_ylabel(f"{city}\n{pid}", fontsize=7)
        for ax in axes[row]: ax.axis("off")

    # legend
    patches = [mpatches.Patch(color=np.array(c)/255, label=n)
               for c, n in zip([[238,238,238],[211,47,47],[255,143,0]],
                                ["Undamaged","Newly damaged","Pre-existing"])]
    fig.legend(handles=patches, loc="lower center", ncol=3,
               bbox_to_anchor=(0.5, -0.02), fontsize=10)

    plt.tight_layout()
    plt.savefig(EVAL_PATH, dpi=150, bbox_inches="tight")
    print(f"Saved qualitative eval → {EVAL_PATH}")


def plot_curves(train_losses, val_losses, save_path):
    fig, ax = plt.subplots(figsize=(8, 4))
    epochs = range(1, len(train_losses)+1)
    ax.plot(epochs, train_losses, label="Train loss", color="#2196F3")
    ax.plot(epochs, val_losses,   label="Val loss",   color="#F44336")
    best = int(np.argmin(val_losses)) + 1
    ax.axvline(best, color="gray", linestyle="--", alpha=0.6, label=f"Best (ep {best})")
    ax.set(xlabel="Epoch", ylabel="Loss", title="Temporal ViT — Cross-Entropy Loss")
    ax.legend(); ax.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    print(f"Saved loss curves → {save_path}")


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    device = get_device()
    print(f"Device: {device}")

    train_ids, val_ids = make_splits()
    print(f"Train: {len(train_ids)}  |  Val: {len(val_ids)}")

    # ── Class weights ──────────────────────────────────────────────────────────
    print("Computing class weights …")
    weights = compute_class_weights(train_ids).to(device)
    print(f"  Class weights: undamaged={weights[0]:.3f}  "
          f"newly={weights[1]:.3f}  pre-existing={weights[2]:.3f}")

    train_ds = TemporalDataset(train_ids, augment=True)
    val_ds   = TemporalDataset(val_ids,   augment=False)
    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE,
                              shuffle=True,  num_workers=0)
    val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE,
                              shuffle=False, num_workers=0)

    # ── Model ──────────────────────────────────────────────────────────────────
    model = TemporalViT(
        img_size=256, patch_size=16, in_channels=2,
        num_classes=NUM_CLASSES, embed_dim=192, depth=4,
        num_heads=6, mlp_ratio=4.0, dropout=0.1,
    ).to(device)
    total = sum(p.numel() for p in model.parameters())
    print(f"TemporalViT parameters: {total:,}")

    criterion = nn.CrossEntropyLoss(weight=weights)
    optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=EPOCHS, eta_min=1e-6)

    train_losses, val_losses = [], []
    best_val_loss = float("inf")
    best_epoch    = 0

    print(f"\n{'Epoch':>5}  {'Train':>8}  {'Val':>8}  LR")
    print("─" * 42)

    for epoch in range(1, EPOCHS + 1):
        train_loss = train_one_epoch(model, train_loader, optimizer, criterion, device)
        val_loss, _, _ = validate(model, val_loader, criterion, device)
        scheduler.step()

        train_losses.append(train_loss)
        val_losses.append(val_loss)

        lr_now = scheduler.get_last_lr()[0]
        marker = " ✓" if val_loss < best_val_loss else ""
        print(f"{epoch:>5}  {train_loss:>8.4f}  {val_loss:>8.4f}  {lr_now:.2e}{marker}")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_epoch    = epoch
            torch.save({"epoch": epoch, "model_state": model.state_dict(),
                        "val_loss": val_loss}, CKPT_PATH)

    print(f"\nBest checkpoint: epoch {best_epoch}  val_loss={best_val_loss:.4f}")

    # ── Final evaluation on best model ─────────────────────────────────────────
    ckpt = torch.load(CKPT_PATH, map_location=device)
    model.load_state_dict(ckpt["model_state"])

    _, all_preds, all_labels = validate(model, val_loader, criterion, device)

    print("\n── Classification Report ──────────────────────────────────")
    report = classification_report(
        all_labels, all_preds,
        target_names=["Undamaged", "Newly damaged", "Pre-existing"],
        digits=3, zero_division=0,
    )
    print(report)

    # ── Plots ──────────────────────────────────────────────────────────────────
    plot_curves(train_losses, val_losses, CURVE_PATH)

    cm = confusion_matrix(all_labels, all_preds)
    plot_confusion(cm, RESULTS_DIR / "vit_confusion_matrix.png")

    plot_qualitative(model, val_ids, device, n=4)


if __name__ == "__main__":
    main()
